@PetAdoptionAPI_HostAddress = http://localhost:5034

GET {{PetAdoptionAPI_HostAddress}}/api/user
Accept: application/json

###

GET {{PetAdoptionAPI_HostAddress}}/api/user/1
Accept: application/json

###

GET {{PetAdoptionAPI_HostAddress}}/api/user/email/alonso.calderon@email.com
Accept: application/json

###

POST {{PetAdoptionAPI_HostAddress}}/api/user/register
Content-Type: application/json

{
  "name": "Alonso Calderon",
  "email": "alonso.calderon@email.com",
  "passwordHash": "newhashedpassword",
  "provider": 1,  
  "providerID": null,
  "role": 1,  
  "createdAt": "2025-02-26T10:00:00Z"
}

###

### Update User (PUT Request)
PUT {{PetAdoptionAPI_HostAddress}}/api/user/1
Content-Type: application/json

{
  "id": 1,
  "name": "Alonso Calderon Updated",
  "email": "alonso.updated@email.com",
  "passwordHash": "newsecurepassword",
  "provider": 0,
  "providerID": null,
  "role": 0,
  "createdAt": "2025-02-26T10:00:00Z"
}



###

DELETE  {{PetAdoptionAPI_HostAddress}}/api/user/1

###